// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChD0KdJuSa6IYPE5KEoGQ_9cW_4SaDWWM',
    appId: '1:391090637096:web:2d85cab34b45ad2815e81d',
    messagingSenderId: '391090637096',
    projectId: 'finora-b15ca',
    authDomain: 'finora-b15ca.firebaseapp.com',
    storageBucket: 'finora-b15ca.firebasestorage.app',
    measurementId: 'G-1DKW7GVG97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNR8r03lbR3iAlU_yeIxA5wCSkDunOy3g',
    appId: '1:391090637096:android:503a63b8c26617f115e81d',
    messagingSenderId: '391090637096',
    projectId: 'finora-b15ca',
    storageBucket: 'finora-b15ca.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pOracRRmtaYfv9h1cQqN9SivWCd6G8k',
    appId: '1:391090637096:ios:14ddff3042a436e715e81d',
    messagingSenderId: '391090637096',
    projectId: 'finora-b15ca',
    storageBucket: 'finora-b15ca.firebasestorage.app',
    androidClientId: '391090637096-8o2dv2dejmg826qtt4o9du4lqhg5i23r.apps.googleusercontent.com',
    iosClientId: '391090637096-v0e0chdc8s5601913185ocve3m9jafk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finora',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7pOracRRmtaYfv9h1cQqN9SivWCd6G8k',
    appId: '1:391090637096:ios:14ddff3042a436e715e81d',
    messagingSenderId: '391090637096',
    projectId: 'finora-b15ca',
    storageBucket: 'finora-b15ca.firebasestorage.app',
    androidClientId: '391090637096-8o2dv2dejmg826qtt4o9du4lqhg5i23r.apps.googleusercontent.com',
    iosClientId: '391090637096-v0e0chdc8s5601913185ocve3m9jafk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChD0KdJuSa6IYPE5KEoGQ_9cW_4SaDWWM',
    appId: '1:391090637096:web:a564df1377026c1515e81d',
    messagingSenderId: '391090637096',
    projectId: 'finora-b15ca',
    authDomain: 'finora-b15ca.firebaseapp.com',
    storageBucket: 'finora-b15ca.firebasestorage.app',
    measurementId: 'G-NSZBKK1PXT',
  );
}
